name: Build Rockos

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 libx11-xcb-dev libx11-dev libgbm-dev libevdev-dev libfmt-dev bear gcc-aarch64-linux-gnu
          pip install pyelftools
          chmod a+x ./workflow.sh
      - name: configure
        run: |
          ./workflow.sh  rock_defconfig
      - name: Build
        run: ./workflow.sh
